the_final_folder/website/config/routes.rb
Website::Application.routes.draw do
  resources :servers
  resources :domains
  resources :users
  root 	:to => 'files#show'
  match '/signin'  => 'sessions#new'     , :via => :get
  match '/signin'  => 'sessions#create'  , :via => :post
  match '/signout' => 'sessions#destroy' , :via => :delete
  match '/files'   => 'files#show'	 , :via => :get
  match '/files/:domain'   => 'files#ls'	 , :via => :get
  match '/files/:domain'   => 'files#put_file'	 , :via => [:post, :put]
  match '/files/:domain'   => 'files#delete'	 , :via => :delete
  match '/get/:domain' => 'files#get_file'       , :via => :get
  match '/download'	=> 'files#download_file' , :via => :get

end

the_final_folder/website/app/models/server.rb
class Server < ActiveRecord::Base
  attr_accessible :domain_id, :ip, :domain_name
  belongs_to :domain
end

the_final_folder/website/app/controllers/servers_controller.rb
class ServersController < ApplicationController
  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    @server = Server.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.json
  def create
    domain = Domain.find_by_name(params[:server][:domain_name])
    params[:server][:domain_id] = domain.id
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, :notice => 'Server was successfully created.' }
        format.json { render :json => @server, :status => :created, :location => @server }
      else
        format.html { render :action => "new" }
        format.json { render :json => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to @server, :notice => 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end
end

the_final_folder/website/app/helpers/servers_helper.rb
module ServersHelper
end

the_final_folder/website/app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :domain_name %><br />
    <%= f.text_field :domain_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

the_final_folder/website/app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

the_final_folder/website/app/views/servers/index.html.erb
<h1>Listing servers</h1>

<table>
  <tr>
    <th>Ip</th>
    <th>Domain</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @servers.each do |server| %>
  <tr>
    <td><%= server.ip %></td>
    <td><%= server.domain_name %></td>
    <td><%= link_to 'Show', server %></td>
    <td><%= link_to 'Edit', edit_server_path(server) %></td>
    <td><%= link_to 'Destroy', server, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Server', new_server_path %>

the_final_folder/website/app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

the_final_folder/website/app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ip:</b>
  <%= @server.ip %>
</p>

<p>
  <b>Domain:</b>
  <%= @server.domain_id %>
</p>


<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>