the_final_folder/website/config/routes.rb
Website::Application.routes.draw do
  resources :servers
  resources :domains
  resources :users
  root 	:to => 'files#show'
  match '/signin'  => 'sessions#new'     , :via => :get
  match '/signin'  => 'sessions#create'  , :via => :post
  match '/signout' => 'sessions#destroy' , :via => :delete
  match '/files'   => 'files#show'	 , :via => :get
  match '/files/:domain'   => 'files#ls'	 , :via => :get
  match '/files/:domain'   => 'files#put_file'	 , :via => [:post, :put]
  match '/files/:domain'   => 'files#delete'	 , :via => :delete
  match '/get/:domain' => 'files#get_file'       , :via => :get
  match '/download'	=> 'files#download_file' , :via => :get

end

the_final_folder/website/app/models/domain.rb
class Domain < ActiveRecord::Base
  attr_accessible :name
  has_many :servers
end

the_final_folder/website/app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @domains }
    end
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    @domain = Domain.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @domain }
    end
  end

  # GET /domains/new
  # GET /domains/new.json
  def new
    @domain = Domain.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @domain }
    end
  end

  # GET /domains/1/edit
  def edit
    @domain = Domain.find(params[:id])
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(params[:domain])

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, :notice => 'Domain was successfully created.' }
        format.json { render :json => @domain, :status => :created, :location => @domain }
      else
        format.html { render :action => "new" }
        format.json { render :json => @domain.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /domains/1
  # PUT /domains/1.json
  def update
    @domain = Domain.find(params[:id])

    respond_to do |format|
      if @domain.update_attributes(params[:domain])
        format.html { redirect_to @domain, :notice => 'Domain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @domain.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy

    respond_to do |format|
      format.html { redirect_to domains_url }
      format.json { head :no_content }
    end
  end
end

the_final_folder/website/app/helpers/domains_helper.rb
module DomainsHelper
end

the_final_folder/website/app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

the_final_folder/website/app/views/domains/edit.html.erb
<h1>Editing domain</h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

the_final_folder/website/app/views/domains/index.html.erb
<h1>Listing domains</h1>

<table>
<tr>
<th>Name</th>
<th></th>
</tr>

<% @domains.each do |domain| %>
<tr>
<td><%= link_to domain.name,'/files/' + domain.name %></td>
<td><%= link_to 'List', domain %></td>
</tr>
<% end %>
</table>

<br />

<%= link_to 'New Domain', new_domain_path %>

the_final_folder/website/app/views/domains/new.html.erb
<h1>New domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

the_final_folder/website/app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @domain.name %> <br />
  <% @domain.servers.each do |serv| %>
	<%= serv.ip%> <br />
  <% end %>

</p>

<%= link_to 'Destroy', @domain, :method => :delete, :data => { :confirm => 'Are you sure?' } %>|
<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>